# build

stages:
  - build
  - deploy
  - test

cache:
  paths:
    - node_modules/
    - ~/.ssh



build:
  image: node:16.13.0
  stage: build
  before_script:
    - npm install
  script:
    - npm run build
    - npm run generate
  artifacts:
    paths:
      - dist/
    when: always


# only run deploy when branch is main

deploy:
  stage: deploy
  image: alpine:latest
  only:
    - main
  needs:
    - build
  dependencies:
    - build
  before_script:
    # add SSH key to known_hosts
    - apk update && apk add openssh-client rsync
    - mkdir -p ~/.ssh
    - touch ~/.ssh/known_hosts
    - eval $(ssh-agent -s)
    - ssh-keyscan ultramarine-linux.org > ~/.ssh/known_hosts
    - echo "$SSH_KEY" | ssh-add -
  script:
    - rsync -avz --delete --progress dist/ gitlab@ultramarine-linux.org:/var/www/ultramarine-site/